name: Endor Labs Scan
on:
  push: 
  workflow_dispatch:

jobs:
  scan-repo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
        
        - name: Checkout Repository
          uses: actions/checkout@v3
          
        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.22.4'
          
        - name: Go Build 
          run: go build
          
        - name: Endor Labs SCA Scan
          uses: endorlabs/github-action@main
          with:
            namespace: "endor-solutions-tsaekao.github"
            api: "https://api.endorlabs.com"
            pr: false
            enable_github_action_token: true
            scan_dependencies: true
            scan_secrets: true
            # scan_git_logs: true # Uncomment to scan git logs for committed secrets
            # scan_github_actions: true # Uncomment to scan GH Action Vulnerabilities
            # scan_tools: true # Uncomment to scan identified tools
            additional_args: "--detached-ref-name=dev" # Additional parameters can be passed with whitespace separation, for example: --github to enable RSPM
